--Create variants table for importing data from snpEff/clinvar annotated VCFs
CREATE TABLE variants (
chr text NULL,
pos INT NULL,
ref text NULL,
alt text NULL,
snp_id text NULL,
ann_allele text NULL,
ann_effect text NULL,
ann_impact text NULL,
ann_gene text NULL,
ann_feature text NULL,
ann_featureid text NULL,
ann_biotype text NULL,
ann_rank text NULL,
ann_hgvs_c text NULL,
ann_hgvs_p text NULL,
ann_cdna_pos text NULL,
ann_cdna_len text NULL,
ann_aa_len text NULL,
ann_distance text NULL,
lof_gene text NULL,
lof_numtr text NULL,
lof_perc text NULL,
clnrevstat text NULL,
rs text NULL,
clndninclorigin text NULL,
origin text NULL,
mc text NULL,
clndn text NULL,
clnvc text NULL,
clnvi text NULL,
af_exac text NULL,
af_esp text NULL,
clnsig text NULL,
clnsigincl text NULL,
clndisdb text NULL,
geneinfo text NULL,
clndisdbincl text NULL,
af_tgp text NULL,
clinhgvs text NULL,
ssr text NULL
);

